#!/bin/bash
# Save this as get_mongo_logs.sh

log_file="/var/log/mongodb/mongod.log"
since=$(date --date='10 minutes ago' '+%Y-%m-%dT%H:%M')

awk -v since="$since" '$0 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}T/ { if ($1 >= since) print }' "$log_file"
